# .bash_profile

[[ -f ~/.bashrc ]] && . ~/.bashrc

PATH=/usr/bin:/usr/sbin:/usr/ucb:/usr/apache-ant-1.9.6/bin:/usr/bin/X11:/sbin:/usr/java_1.7.2/bin:/opt/freeware/bin:.
[[ -d ~/bin ]] && PATH=~/bin:/usr/local/bin:"${PATH}"
export PATH
